version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app  
    ports:
      - "8000:8000"
    depends_on:
      - db
      - neo4j
    environment:
      - DEBUG=True
      - SECRET_KEY=24h
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=
      - MONGODB_URI=mongodb://db:27017/candidate

  db:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  neo4j:
    image: neo4j:latest
    volumes:
      - neo4j_data:/data
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/

volumes:
  mongodb_data:
  neo4j_data:
